# version: "3.8"

services:
  # Speech-to-Text (STT) Service
  stt:
    image: sst_image
    container_name: stt_service
    build:
      context: ./stt
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./stt/models:/app/models
    networks:
      - elderly_care_network
    environment:
      - STT_MODEL_PATH=/app/models/vosk-model-en
    command: python stt_server.py

  # Text-to-Speech (TTS) Service
  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: tts_image
    ports:
      - "5003:5003"
    networks:
      - elderly_care_network
    environment:
      - TTS_MODEL_PATH=/app/models/coqui-tts
    command: python3 tts_server.py

  # Large Language Model (LLM) Service
  llm:
    image: llm_image
    container_name: llm_service
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - elderly_care_network
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    command: python llm_server.py

  # Ollama Service
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - elderly_care_network

  # Database Service (PostgreSQL)
  database:
    image: postgres:latest
    container_name: elderly_care_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - elderly_care_network
    environment:
      POSTGRES_USER: elderly_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: elderly_care_db

  # Matrix Protocol Service (Synapse)
  matrix:
    build: ./matrix
    depends_on:
      - database
      - llm
      - stt
      - tts
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=elderly_user
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=elderly_care_db
    ports:
      - "5004:5004"
    volumes:
      - ./matrix/store:/data/matrix-store
    networks:
      - elderly_care_network
  # matrix-synapse homeserver
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    volumes:
      - ./synapse/data:/data
    ports:
      - "8008:8008"
    networks:
      - elderly_care_network

# Docker Network
networks:
  elderly_care_network:
    driver: bridge
volumes:
  ollama_data:
