# version: "3.8"

services:
  # Speech-to-Text (STT) Service
  stt_vosk:
    image: sst_image
    container_name: stt_service
    build:
      context: ./stt
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./stt/models:/app/models
    networks:
      - elderly_care_network
    environment:
      - STT_MODEL_PATH=/app/models/vosk-model-en
    command: python stt_server.py
  stt_fastwhisper:
    container_name: stt_fastwhisper_service
    build:
      context: ./fastwhisper_stt
      dockerfile: Dockerfile
    image: fastwhisper_stt_image
    ports:
      - "5004:5001" # internal 5001 but external 5004 to avoid LLM service (LLM using 5001)
    networks:
      - elderly_care_network
    command: gunicorn --bind 0.0.0.0:5001 stt_server:app

  # Text-to-Speech (TTS) Service
  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    image: tts_image
    ports:
      - "5003:5003"
    networks:
      - elderly_care_network
    environment:
      - TTS_MODEL_PATH=/app/models/coqui-tts
    command: python3 tts_server.py

  # Large Language Model (LLM) Service
  llm:
    build:
      context: ./llm
    image: llm_image
    container_name: llm_service
    ports:
      - "5001:5001"
    networks:
      - elderly_care_network
    command: uvicorn llm_server:app --host 0.0.0.0 --port 5002 --log-level debug

  # Ollama Service
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - elderly_care_network

  # Database Service (PostgreSQL)
  database:
    image: postgres:latest
    container_name: elderly_care_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - elderly_care_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  assistant:
    build: ./assistant
    ports:
      - "8000:8000"
    networks:
      - elderly_care_network
    depends_on:
      # choose one stt
      # - stt_vosk
      - stt_fastwhisper
      - llm
      - tts
    command: uvicorn ws_server:app --host 0.0.0.0 --port 8000

# Docker Network
networks:
  elderly_care_network:
    driver: bridge
volumes:
  ollama_data:
